name: CMake Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system OpenGL
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev ninja-build cmake

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
      - name: Configure
        run: >
          cmake -B build
          -S .
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Upload build folder
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.build_type }}
          path: build
